// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lferuhxmkjklnvhbynqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmZXJ1aHhta2prbG52aGJ5bnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDczNjUsImV4cCI6MjA2Mjc4MzM2NX0._ofMWH5E8AsZdsP39YAXJaefoquP5NU7JYhBF-OO2P8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);