// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxqlyugswqfdxjegeaev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4cWx5dWdzd3FmZHhqZWdlYWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTk0ODIsImV4cCI6MjA2MzA3NTQ4Mn0.GAy5Mg4bY-OndPYPlXwy2AIZpLa5K2hYZ0D1SjvvxHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);